<a href="https://colab.research.google.com/github/ArunimaDas611/Hack-O-Week-Semester-V-Odd-Semester-Session-2026-27/blob/main/Hack_o_Week(13%2614).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost as xgb

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from xgboost import XGBClassifier

%matplotlib inline
sns.set_style('whitegrid')

In [ ]:
df = pd.read_csv('Train.csv')
df.head()

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1,Segmentation
0,462809,Male,No,22,No,Healthcare,1.0,Low,4.0,Cat_4,D
1,462643,Female,Yes,38,Yes,Engineer,NaN,Average,3.0,Cat_4,A
2,466315,Female,Yes,67,Yes,Engineer,1.0,Low,1.0,Cat_6,B
3,461735,Male,Yes,67,Yes,Lawyer,0.0,High,2.0,Cat_6,B
4,462669,Female,Yes,40,Yes,Entertainment,NaN,High,6.0,Cat_6,A

In [ ]:
df.describe()

                  ID          Age  Work_Experience  Family_Size
count    8068.000000  8068.000000      7239.000000  7733.000000
mean   463479.214551    43.466906         2.641663     2.850123
std      2595.381232    16.711696         3.406763     1.531413
min    458982.000000    18.000000         0.000000     1.000000
25%    461240.750000    30.000000         0.000000     2.000000
50%    463472.500000    40.000000         1.000000     3.000000
75%    465744.250000    53.000000         4.000000     4.000000
max    467974.000000    89.000000        14.000000     9.000000

In [ ]:
df['Segmentation'] = df['Segmentation'].map({'A':0, 'B':1, 'C':2, 'D':3})
df['Gender'] = df['Gender'].map({'Male':0, 'Female':1})
df['Ever_Married'] = df['Ever_Married'].map({'No':0, 'Yes':1})
df['Graduated'] = df['Graduated'].map({'No':0, 'Yes':1})
df['Profession'] = df['Profession'].map({'Healthcare':0, 'Engineer':1, 'Lawyer':2, 'Entertainment':3, 'Artist':4, 'Executive':5, 'Doctor':6, 'Homemaker':7, 'Marketing':8})
df['Spending_Score'] = df['Spending_Score'].map({'Low':0, 'Average':1, 'High':2})

In [ ]:
X = df.drop(columns=['Var_1', 'Segmentation'])
y = df[['Segmentation']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
params = {
    'objective':'binary:logistic',
    'max_depth':4,
    'learning_rate':0.1,
    'n_estimators':100,
    'alpha':10
}

model = XGBClassifier(**params)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0], got [nan]