<a href="https://colab.research.google.com/github/ArunimaDas611/Hack-O-Week-Semester-V-Odd-Semester-Session-2026-27/blob/main/Week9and10(Hack_o_Week).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

df = pd.read_csv('Dummy Data HSS.csv')
df.head()

     TV      Radio  Social Media Influencer       Sales
0  16.0   6.566231      2.907983       Mega   54.732757
1  13.0   9.237765      2.409567       Mega   46.677897
2  41.0  15.886446      2.913410       Mega  150.177829
3  83.0  30.020028      6.922304       Mega  298.246340
4  15.0   8.437408      1.405998      Micro   56.594181

In [ ]:
df.isnull().sum()

TV              10
Radio            4
Social Media     6
Influencer       0
Sales            6
dtype: int64

In [ ]:
df.dropna(inplace=True)
le = LabelEncoder()

df['Influencer'] = le.fit_transform(df['Influencer'])
df.head()

     TV      Radio  Social Media  Influencer       Sales
0  16.0   6.566231      2.907983           1   54.732757
1  13.0   9.237765      2.409567           1   46.677897
2  41.0  15.886446      2.913410           1  150.177829
3  83.0  30.020028      6.922304           1  298.246340
4  15.0   8.437408      1.405998           2   56.594181

In [ ]:
#Train-Test Split & Cross-Validation
X = df[['TV', 'Radio', 'Social Media', 'Influencer']]

y = df['Sales']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

model1 = LinearRegression()
scores1 = cross_val_score(model1, X, y, cv=5)
print(scores1)

model2 = Ridge(alpha=1.0)
scores2 = cross_val_score(model2, X, y, cv=5)
print("\n", scores2)

model3 = RandomForestRegressor(max_depth=2, random_state=42)
scores3 = cross_val_score(model3, X, y, cv=5)
print("\n", scores3)

[0.99899971 0.99898634 0.9990183  0.99900784 0.99894819]

 [0.99899971 0.99898634 0.9990183  0.99900784 0.99894819]

 [0.94647763 0.94303923 0.94482411 0.94289587 0.94009099]

In [ ]:
print("Linear Regression")
print(f"Accuracy: {scores1.mean().round(3)}, Standard Deviation: {scores1.std().round()}\n\n")

print("Ridge Regression")
print(f"Accuracy: {scores2.mean().round(3)}, Standard Deviation: {scores2.std().round()}\n\n")

print("Random Forest Classification")
print(f"Accuracy: {scores3.mean().round(3)}, Standard Deviation: {scores3.std().round()}\n\n")

Linear Regression
Accuracy: 0.999, Standard Deviation: 0.0


Ridge Regression
Accuracy: 0.999, Standard Deviation: 0.0


Random Forest Classification
Accuracy: 0.943, Standard Deviation: 0.0

In [ ]:
model1.fit(X_train, y_train)
y_pred1 = model1.predict(X_test)

model2.fit(X_train, y_train)
y_pred2 = model2.predict(X_test)

model3.fit(X_train, y_train)
y_pred3 = model3.predict(X_test)

bins = [0, 100.0, 200.0, 300.0, 400.0]
y_test_binned = pd.cut(y_test, bins = bins)
y_pred1_binned = pd.cut(y_pred1, bins = bins)
y_pred2_binned = pd.cut(y_pred2, bins = bins)
y_pred3_binned = pd.cut(y_pred3, bins = bins)

In [ ]:
y_test_binned

625     (200.0, 300.0]
1668    (200.0, 300.0]
557     (100.0, 200.0]
2976    (100.0, 200.0]
3064    (100.0, 200.0]
             ...
1014    (200.0, 300.0]
1088    (300.0, 400.0]
2734    (200.0, 300.0]
3078      (0.0, 100.0]
2280    (300.0, 400.0]
Name: Sales, Length: 1137, dtype: category
Categories (4, interval[float64, right]): [(0.0, 100.0] < (100.0, 200.0] < (200.0, 300.0] <
                                           (300.0, 400.0]]

In [ ]:
cm1 = confusion_matrix(y_test_binned, y_pred1_binned)
cm2 = confusion_matrix(y_test_binned, y_pred2_binned)
cm3 = confusion_matrix(y_test_binned, y_pred3_binned)

disp1 = ConfusionMatrixDisplay(confusion_matrix=cm1, display_labels=model1.classes_)
disp2 = ConfusionMatrixDisplay(confusion_matrix=cm2, display_labels=model2.classes_)
disp3 = ConfusionMatrixDisplay(confusion_matrix=cm3, display_labels=model3.classes_)

disp1.plot()
disp2.plot()
disp3.plot()

ValueError: unknown is not supported